// comments
export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENT_BY_ID = "FETCH_COMMENT_BY_ID";
export const FETCH_COMMENTS_BY_ISSUE_ID = "FETCH_COMMENTS_BY_ISSUE_ID";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";

// issues
export const FETCH_ISSUES = "FETCH_ISSUES";
export const FETCH_ISSUE_BY_ID = "FETCH_ISSUE_BY_ID";
export const FETCH_ISSUES_BY_PROJECT_ID = "FETCH_ISSUES_BY_PROJECT_ID";
export const CREATE_ISSUE = "CREATE_ISSUE";
export const UPDATE_ISSUE = "UPDATE_ISSUE";
export const DELETE_ISSUE = "DELETE_ISSUE";

// priority
export const FETCH_PRIORITIES = "FETCH_PRIORITIES";
export const FETCH_PRIORITY_BY_ID = "FETCH_PRIORITY_BY_ID";

// projects
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const FETCH_PROJECT_BY_ID = "FETCH_PROJECT_BY_ID";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

// roles
export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLE_BY_ID = "FETCH_ROLE_BY_ID";

// status
export const FETCH_STATUS = "FETCH_STATUS";
export const FETCH_STATUS_BY_ID = "FETCH_STATUS_BY_ID";

// userIssues
export const FETCH_USERISSUES = "FETCH_USER_ISSUES";
export const FETCH_USERISSUES_BY_USER_ID = "FETCH_USERISSUE_BY_USER_ID";
export const FETCH_USERISSUES_BY_ISSUE_ID = "FETCH_USERISSUE_BY_ISSUE_ID";
export const FETCH_USERISSUE_BY_USER_AND_ISSUE_ID =
  "FETCH_USERISSUE_BY_USER_AND_ISSUE_ID";
export const ASSIGN_USER_TO_ISSUE = "ASSIGN_USER_TO_ISSUE";
export const REMOVE_USER_FROM_ISSUE = "REMOVE_USER_FROM_ISSUE";

// userProjects
export const FETCH_USERPROJECTS = "FETCH_USERPROJECTS";
export const FETCH_USERPROJECTS_BY_USER_ID = "FETCH_USERPROJECTS_BY_USER_ID";
export const FETCH_USERPROJECTS_BY_PROJECT_ID =
  "FETCH_USERPROJECTS_BY_PROJECT_ID";
export const FETCH_USERPROJECT_BY_USER_AND_PROJECT_ID =
  "FETCH_USERPROJECT_BY_USER_AND_PROJECT_ID";
export const ASSIGN_USER_TO_PROJECT = "ASSIGN_USER_TO_PROJECT";
export const UPDATE_USER_EXIT_PROJECT_DATE = "UPDATE_USER_EXIT_PROJECT_DATE";

// user
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER_BY_ID = "FETCH_USER_BY_ID";
// TODO: quite a few todos in api so will complete later.
